/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ArtworkCreateNestedManyWithoutArtistsInput } from "./ArtworkCreateNestedManyWithoutArtistsInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ProjectCreateNestedManyWithoutArtistsInput } from "./ProjectCreateNestedManyWithoutArtistsInput";

@InputType()
class ArtistCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  artistStatements?: string | null;

  @ApiProperty({
    required: false,
    type: () => ArtworkCreateNestedManyWithoutArtistsInput,
  })
  @ValidateNested()
  @Type(() => ArtworkCreateNestedManyWithoutArtistsInput)
  @IsOptional()
  @Field(() => ArtworkCreateNestedManyWithoutArtistsInput, {
    nullable: true,
  })
  artworks?: ArtworkCreateNestedManyWithoutArtistsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bioData?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  bioPdf?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  cvData?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  cvPdf?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProjectCreateNestedManyWithoutArtistsInput,
  })
  @ValidateNested()
  @Type(() => ProjectCreateNestedManyWithoutArtistsInput)
  @IsOptional()
  @Field(() => ProjectCreateNestedManyWithoutArtistsInput, {
    nullable: true,
  })
  projects?: ProjectCreateNestedManyWithoutArtistsInput;
}

export { ArtistCreateInput as ArtistCreateInput };
