/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { JournalService } from "../journal.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JournalCreateInput } from "./JournalCreateInput";
import { Journal } from "./Journal";
import { JournalFindManyArgs } from "./JournalFindManyArgs";
import { JournalWhereUniqueInput } from "./JournalWhereUniqueInput";
import { JournalUpdateInput } from "./JournalUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class JournalControllerBase {
  constructor(
    protected readonly service: JournalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Journal })
  @nestAccessControl.UseRoles({
    resource: "Journal",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createJournal(
    @common.Body() data: JournalCreateInput
  ): Promise<Journal> {
    return await this.service.createJournal({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        brewMethod: true,
        brewTime: true,
        coffeeName: true,
        content: true,
        createdAt: true,
        grindSize: true,
        id: true,
        notes: true,
        rating: true,
        roastDate: true,
        roaster: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        waterTemperature: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Journal] })
  @ApiNestedQuery(JournalFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Journal",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async journals(@common.Req() request: Request): Promise<Journal[]> {
    const args = plainToClass(JournalFindManyArgs, request.query);
    return this.service.journals({
      ...args,
      select: {
        brewMethod: true,
        brewTime: true,
        coffeeName: true,
        content: true,
        createdAt: true,
        grindSize: true,
        id: true,
        notes: true,
        rating: true,
        roastDate: true,
        roaster: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        waterTemperature: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Journal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Journal",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async journal(
    @common.Param() params: JournalWhereUniqueInput
  ): Promise<Journal | null> {
    const result = await this.service.journal({
      where: params,
      select: {
        brewMethod: true,
        brewTime: true,
        coffeeName: true,
        content: true,
        createdAt: true,
        grindSize: true,
        id: true,
        notes: true,
        rating: true,
        roastDate: true,
        roaster: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        waterTemperature: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Journal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Journal",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateJournal(
    @common.Param() params: JournalWhereUniqueInput,
    @common.Body() data: JournalUpdateInput
  ): Promise<Journal | null> {
    try {
      return await this.service.updateJournal({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          brewMethod: true,
          brewTime: true,
          coffeeName: true,
          content: true,
          createdAt: true,
          grindSize: true,
          id: true,
          notes: true,
          rating: true,
          roastDate: true,
          roaster: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          waterTemperature: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Journal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Journal",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteJournal(
    @common.Param() params: JournalWhereUniqueInput
  ): Promise<Journal | null> {
    try {
      return await this.service.deleteJournal({
        where: params,
        select: {
          brewMethod: true,
          brewTime: true,
          coffeeName: true,
          content: true,
          createdAt: true,
          grindSize: true,
          id: true,
          notes: true,
          rating: true,
          roastDate: true,
          roaster: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          waterTemperature: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
